export const LOADING_STARTS = 'LOADING_STARTS';
export const LOADING_ENDS = 'LOADING_ENDS';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_ERROR = 'FETCH_USER_DETAILS_ERROR';
export const DELETE_USER_DETAILS = 'DELETE_USER_DETAILS';
export const EDIT_USER_DETAILS = 'EDIT_USER_DETAILS';